### ISSUE TITLE
Server .14 Chunks not loading

### ISSUE THREAD

**Issue by meetloaf13** [BukkitPE/BukkitPE#25]
So I just updated my server to the latest .14, I also updated to the latest 'bin' folder.

None of the chunks after the initial chunk-load are loading.  Any ideas?  I typically load a pretty generous amount of chunks so that we have a decent view distance. 

I didn't change my bukkitPE.yml at all.

Thanks,

**Comment by MunkySkunk** [comment]
I have the same issue since the update

**Comment by meetloaf13** [comment]
I just reconnected for the 4th time.  More chunks are loading and as I continue to explore they continue to load...however my view distance is severely nerfed, 

Also, chunks are disappearing at an incredible clip.

**Comment by meetloaf13** [comment]
Thought maybe the php.ini had a hard memory limit that was too low.  I've never had any luck setting:
memory_limit = 256M
to anything other than above.  Tried '0M' '4096' and others (I have 16GB RAM).

So obviously it didn't help the above problem, fwiw.

**Comment by meetloaf13** [comment]
https://github.com/ClearSkyTeam/ClearSky/issues/187

**Comment by xZeroMCPE** [comment]
I think that this is being affected by the 14.0 Update, But anyway i've tested it myself and had same issue you guys are having.. I will be working on a fix for it and keep you updated today with it.

**Comment by meetloaf13** [comment]
It seems to be better but still not good, at least for me.

**Comment by meetloaf13** [comment]
So I deleted my. 0.13 yml and let it generate a new one. It helps, but Im still having issues. 

I'm trying to make it so chunks are loaded far off into the distance and stay loaded. my clients have distance set to max as does the server.propeties. What are the chunks settings i  need to alter to fix this?

**Comment by xZeroMCPE** [comment]
Can i see your BukkitPE.ym?

**Comment by meetloaf13** [comment]
`####
# There are the main settings for BukkitPE, If you made a mistake just delete it and the default config will come
# back. Do not touch if you don't know what you are doing
###

######
# Query plugins makes server listing sites know the plugin you're using.
######
# ShutDown-Message is the message the player will recieve when server shuts down.
######
settings:
 language: "eng"
 force-language: false
 shutdown-message: "BukkitPE server closed."
 query-plugins: true
 deprecated-verbose: true
 enable-profiling: false
 profile-report-trigger: 20
 async-workers: auto
 ######
# toggles hunger and regeneration on and off.
######
hunger:
 enable: true
######
# Turns XP on and off aswell as setting what drops XP.
######
experience:
 enable: true
 player-drop: true
 mob-drop: true
 break-drop: true
 smelt-drop: true
######
# toggles redstone on your server.
######
redstone:
 enable: true
######
# toggles weather swtich on your server.
######
weather:
 enable: true
 
 rain:
  possibility: 10
 
  time:
   min: 30
   max: 120
   
  rainfall:
   min: 1000
   max: 100000
 
I/O:
 title-usage: true
 log-to-file: true
###
# Increase the Main-Hard-Limit to alocate much ram you wan't BukkitPE to use. Ex: 2048 = 2GB
###
memory:
 global-limit: 0
 main-limit: 0
 main-hard-limit: 2048
 check-rate: 600
 continuous-trigger: true
 continuous-trigger-rate: 30

 garbage-collection:
  period: 36000
  collect-async-worker: true
  low-memory-trigger: true

 max-chunks:
  trigger-limit: 128
  trigger-chunk-collect: true
  low-memory-trigger: true

 world-caches:
  disable-chunk-cache: true
  low-memory-trigger: true


network:
 batch-threshold: 256
 compression-level: 7
 async-compression: true
 upnp-forwarding: false

debug:
 level: 1
 allow-xdebug: false
 #Enables /status, /gc
 commands: true

level-settings:
 default-format: mcregion
 convert-format: false
 auto-tick-rate: true
 auto-tick-rate-limit: 20
 base-tick-rate: 1
 always-tick-players: false

chunk-sending:
 per-tick: 16
 max-chunks: 128
 spawn-threshold: 56
 cache-chunks: true

chunk-ticking:
 per-tick: 8
 tick-radius: 8
 light-updates: false
 clear-tick-list: true

chunk-generation:
 queue-size: 2
 population-queue-size: 1

ticks-per:
 animal-spawns: 400
 monster-spawns: 1
 autosave: 6000
 cache-cleanup: 900
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15

auto-report:
 #Send crash reports for processing
 enabled: false
 send-code: true
 send-settings: true
 send-phpinfo: false
 host: crash.BukkitPE.net

anonymous-statistics:
 #Sends anonymous statistics for data aggregation, plugin usage tracking
 enabled: false
 host: stats.BukkitPE.net

auto-updater:
 enabled: false
 on-update:
  warn-console: true
  warn-ops: true
 #Can be development, beta or stable.
 preferred-channel: beta
 #If using a development version, it will suggest changing the channel
 suggest-channels: true
 host: www.BukkitPE.net

aliases:
 #Examples:
 #showtheversion: version
 #savestop: [save-all, stop]

worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 #world:
 # seed: 404
 # generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)`

**Comment by meetloaf13** [comment]
Here you go (16 GB ram, i7 2700K Beast)
http://pastebin.com/bZELei9q

**Comment by xZeroMCPE** [comment]
Try this BukkitPE.yml http://pastebin.com/5ft7HVfd

**Comment by meetloaf13** [comment]
Thanks for that. Chunks are loading pretty well as far as speed, the range isn't great, not only as you're moving forward, but the chunks behind you disappear rather quickly.  This is a bit of a deal breaker for my kids, since they get lost pretty easily with limited view distance.

This happened: http://imgur.com/gKPV9yK the server still wouldn't load that particular chunk?

i cant ever change the max memory variable, i always get a php error saying out of memory.  really odd.

**Comment by MunkySkunk** [comment]
I am still having real problems with the chunks loading since the update.

**Comment by xZeroMCPE** [comment]
Hi, i've tested it myself with a power hardware, but having the same issue. I think it must of been the 0.14 update which has been causing that issue... Give my team some time while we try a way to fix it thanks.

**Comment by meetloaf13** [comment]
Thanks Andre

**Comment by MunkySkunk** [comment]
Thank you 👍

**Comment by DelxHQ** [comment]
is this still a issue?

**Comment by xZeroMCPE** [comment]
Fixed.

**Comment by DelxHQ** [comment]
This is not fixed @AndreTheGamer. Please stop telling them its fixed just to clear the issues

**Comment by xZeroMCPE** [comment]
Having same issue, Will try to fix this as soon am home.

**Comment by xZeroMCPE** [comment]
Issue has been fixed i couldn't want till i got home so i just got it done at class. Anyway there isn't a phar as of now. But maybe DelxHQ might already be testing it/making a phar :P  

[d8c58f7](https://github.com/BukkitPE/BukkitPE/commit/d8c58f7e0cbe9dbc87e80cc8cfbddb7804487498)
